### ISSUE TITLE
Crashes server and client

### ISSUE THREAD

**Issue by Rodzioo** [Elecs-Mods/CraftingTable-IV#22] opened 2016-01-10 16:33 UTC
http://pastebin.com/kQJJxsJc
Using CraftingTableIV-1.7.10-1.1Beta.74.jar
and ElecCore-1.7.10-1.4.176.jar

**Comment by Elec332** [comment] 2016-01-10 19:01
Duplicate of #20 closing this one :)

**Closed as completed by Elec332** 2016-01-10 19:01 UTC
Labels: duplicate
