### ISSUE TITLE
Enormous lags

### ISSUE THREAD

**Issue by LUEZIS** [Elecs-Mods/CraftingTable-IV#98] opened 2020-05-13 20:13 UTC
It seems like your mod causes a game lag-session with a specific mods like Overmod or Aggressive Furries mod (better don't ask). Here is the crashlog:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  wings (wings-1.1.6-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  LoadingPlugin (BetterPvP_20.10.0_Forge_1.12.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MistHookLoader (MistyWorld-1.12.2-1.2.4.6.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ratscore (rats-3.2.11-1.12.2.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.18.jar)
  CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.0-core.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/12/20 8:47 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at elec332.craftingtableiv.CraftingTableIV.getItemIdentifier(CraftingTableIV.java:206)
	at elec332.craftingtableiv.util.FastRecipeList.addRecipe(FastRecipeList.java:39)
	at elec332.craftingtableiv.handler.CraftingHandler.rebuildList(CraftingHandler.java:104)
	at elec332.craftingtableiv.CraftingTableIV.reloadRecipes(CraftingTableIV.java:151)
	at elec332.craftingtableiv.network.PacketInitRecipes.onMessageThreadSafe(PacketInitRecipes.java:16)
	at elec332.core.network.packets.AbstractPacket$1.run(AbstractPacket.java:34)
	at elec332.core.handler.TickHandler.processSingleTicks(TickHandler.java:88)
	at elec332.core.handler.TickHandler.access$100(TickHandler.java:17)
	at elec332.core.handler.TickHandler$1.onTickClient(TickHandler.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2220__onTickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at elec332.craftingtableiv.CraftingTableIV.getItemIdentifier(CraftingTableIV.java:206)
	at elec332.craftingtableiv.util.FastRecipeList.addRecipe(FastRecipeList.java:39)
	at elec332.craftingtableiv.handler.CraftingHandler.rebuildList(CraftingHandler.java:104)
	at elec332.craftingtableiv.CraftingTableIV.reloadRecipes(CraftingTableIV.java:151)
	at elec332.craftingtableiv.network.PacketInitRecipes.onMessageThreadSafe(PacketInitRecipes.java:16)
	at elec332.core.network.packets.AbstractPacket$1.run(AbstractPacket.java:34)
	at elec332.core.handler.TickHandler.processSingleTicks(TickHandler.java:88)
	at elec332.core.handler.TickHandler.access$100(TickHandler.java:17)
	at elec332.core.handler.TickHandler$1.onTickClient(TickHandler.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2220__onTickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lufik'/53038, l='MpServer', x=-279.38, y=68.00, z=-396.76]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-223,64,-321), Chunk: (at 1,4,15 in -14,-21; contains blocks -224,0,-336 to -209,255,-321), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 13664 game time, 13664 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 98 total; [EntityItem['item.tile.gravel'/51713, l='MpServer', x=-241.88, y=35.00, z=-458.44], EntityItem['item.tile.gravel'/51714, l='MpServer', x=-241.21, y=35.00, z=-456.09], EntityBat['Bat'/51715, l='MpServer', x=-254.36, y=36.03, z=-435.29], EntityItem['item.tile.gravel'/51716, l='MpServer', x=-249.13, y=53.00, z=-443.08], EntityItem['item.tile.gravel'/51717, l='MpServer', x=-252.88, y=52.00, z=-443.39], EntityItem['item.tile.gravel'/51718, l='MpServer', x=-250.25, y=53.00, z=-442.51], EntityItem['item.tile.gravel'/51719, l='MpServer', x=-247.88, y=52.00, z=-442.75], EntityHull['unknown'/51720, l='MpServer', x=-244.35, y=66.00, z=-436.35], EntityItem['item.tile.dungeontactics:bush_incindiberry'/51721, l='MpServer', x=-255.80, y=12.00, z=-430.57], EntityBat['Bat'/51722, l='MpServer', x=-242.53, y=25.10, z=-426.55], EntityItem['item.tile.gravel'/51506, l='MpServer', x=-342.66, y=38.00, z=-449.88], EntityItem['item.tile.gravel'/51508, l='MpServer', x=-338.11, y=30.00, z=-435.84], EntityItem['item.tile.gravel'/51509, l='MpServer', x=-336.88, y=30.00, z=-436.18], EntityItem['item.tile.gravel'/51511, l='MpServer', x=-340.88, y=33.00, z=-432.21], EntityItem['item.tile.gravel'/51512, l='MpServer', x=-339.46, y=33.00, z=-432.48], EntityItem['item.tile.gravel'/51513, l='MpServer', x=-341.88, y=33.00, z=-434.28], EntityItem['item.tile.gravel'/51514, l='MpServer', x=-341.84, y=33.00, z=-435.46], EntityItem['item.tile.gravel'/51515, l='MpServer', x=-339.72, y=31.00, z=-431.88], EntityItem['item.tile.gravel'/51516, l='MpServer', x=-338.40, y=33.00, z=-430.01], EntityItem['item.tile.mushroom7'/51520, l='MpServer', x=-342.19, y=21.00, z=-395.53], EntityItem['item.tile.torch'/51521, l='MpServer', x=-342.13, y=51.00, z=-375.43], EntityPlayerSP['Lufik'/53038, l='MpServer', x=-279.38, y=68.00, z=-396.76], MoCEntityManderin['unknown'/51523, l='MpServer', x=-338.50, y=61.61, z=-344.50], EntityEmana['unknown'/51534, l='MpServer', x=-327.38, y=59.50, z=-449.42], EntityItem['item.tile.mushroom12'/51535, l='MpServer', x=-323.13, y=21.42, z=-434.68], EntityItem['item.tile.mushroom.glowshroom'/51536, l='MpServer', x=-329.13, y=50.29, z=-435.13], EntityItem['item.tile.mushroom.glowshroom'/51537, l='MpServer', x=-330.41, y=50.36, z=-434.13], EntityItem['item.tile.mushroom.glowshroom'/51538, l='MpServer', x=-327.80, y=50.00, z=-440.49], MoCEntityOstrich['unknown'/51539, l='MpServer', x=-329.50, y=68.00, z=-430.50], EntityItem['item.tile.flower_1.miners_delight'/51540, l='MpServer', x=-323.50, y=54.00, z=-387.88], EntityItem['item.item.string'/51541, l='MpServer', x=-321.70, y=9.00, z=-369.41], EntityItem['item.item.string'/51542, l='MpServer', x=-320.85, y=8.70, z=-369.25], EntityItem['item.tile.gravel'/51543, l='MpServer', x=-322.42, y=8.00, z=-371.43], EntityItem['item.item.string'/51544, l='MpServer', x=-323.58, y=8.00, z=-367.50], EntityItem['item.item.string'/51545, l='MpServer', x=-321.88, y=8.66, z=-367.13], EntityItem['item.item.string'/51546, l='MpServer', x=-320.41, y=8.67, z=-365.82], EntityItem['item.item.string'/51547, l='MpServer', x=-321.75, y=8.70, z=-363.77], EntityItem['item.item.string'/51548, l='MpServer', x=-323.64, y=8.69, z=-363.25], EntityItem['item.item.string'/51549, l='MpServer', x=-323.54, y=8.66, z=-365.57], EntitySturgeon['Sturgeon'/51550, l='MpServer', x=-331.36, y=59.12, z=-357.25], EntityHull['unknown'/51579, l='MpServer', x=-306.02, y=36.00, z=-443.60], EntityHull['unknown'/51580, l='MpServer', x=-311.99, y=17.00, z=-420.59], EntityCyberSkeleton['unknown'/51581, l='MpServer', x=-306.77, y=50.00, z=-413.44], EntityAncientGolem['Ancient Golem'/51583, l='MpServer', x=-317.50, y=21.00, z=-348.50], EntityNautilus['Nautilus'/51584, l='MpServer', x=-316.39, y=57.80, z=-337.46], EntityItem['item.item.grassfiber'/51591, l='MpServer', x=-290.92, y=14.00, z=-458.76], EntityTumbleweed['unknown'/51592, l='MpServer', x=-291.99, y=65.53, z=-460.30], EntityTumbleweed['unknown'/51593, l='MpServer', x=-293.99, y=64.32, z=-458.99], EntityItem['item.tile.rustic.grape_stem'/51594, l='MpServer', x=-293.89, y=13.00, z=-432.00], EntityItem['item.item.crystal_essence'/51595, l='MpServer', x=-291.13, y=13.00, z=-439.43], EntityItem['item.item.crystal_essence'/51596, l='MpServer', x=-290.57, y=30.00, z=-441.04], EntityHull['unknown'/51597, l='MpServer', x=-301.65, y=13.00, z=-427.10], EntityBat['Bat'/51598, l='MpServer', x=-302.75, y=15.07, z=-420.25], EntityArchaeologist['Archaeologist'/51599, l='MpServer', x=-294.00, y=16.00, z=-432.00], EntityAlafha['unknown'/51600, l='MpServer', x=-304.33, y=24.12, z=-426.56], EntityItem['item.tile.flower_1.miners_delight'/51601, l='MpServer', x=-301.34, y=30.00, z=-423.97], EntityItem['item.item.raw_bat'/51602, l='MpServer', x=-300.88, y=11.00, z=-401.50], EntityItem['item.item.l_essence_of_greed'/51603, l='MpServer', x=-300.48, y=9.00, z=-403.43], EntityBat['Bat'/51604, l='MpServer', x=-297.04, y=12.58, z=-408.66], EntityItem['item.tile.dungeontactics:bush_incindiberry'/51605, l='MpServer', x=-299.50, y=30.00, z=-413.55], EntityCustom['unknown'/51606, l='MpServer', x=-289.53, y=35.00, z=-396.29], EntityNogla['unknown'/51607, l='MpServer', x=-288.50, y=31.00, z=-354.50], Entity_SpecialSkeleton['unknown'/51608, l='MpServer', x=-301.50, y=19.00, z=-364.50], EntityStoneling['Stoneling'/51609, l='MpServer', x=-289.50, y=20.00, z=-361.50], EntityItem['item.tile.mushroom.glowshroom'/51610, l='MpServer', x=-300.56, y=62.67, z=-361.41], EntityNogla['unknown'/51611, l='MpServer', x=-299.50, y=34.00, z=-335.50], EntityItem['item.tile.gravel'/51620, l='MpServer', x=-280.88, y=18.88, z=-416.88], EntityItem['item.tile.mushroom.glowshroom'/51621, l='MpServer', x=-273.22, y=19.00, z=-420.88], EntityItem['item.item.stick'/51622, l='MpServer', x=-281.70, y=19.00, z=-423.22], EntityItem['item.tile.sapling.oak'/51623, l='MpServer', x=-282.47, y=19.00, z=-423.41], EntityBat['Bat'/51624, l='MpServer', x=-285.34, y=34.86, z=-417.66], EntityItem['item.item.seeds_pumpkin'/51625, l='MpServer', x=-287.63, y=65.00, z=-422.42], EntityItem['item.tile.cavevine'/51626, l='MpServer', x=-284.88, y=33.00, z=-408.88], EntityFarlander['unknown'/51627, l='MpServer', x=-284.50, y=67.00, z=-403.36], EntityFarlander['unknown'/51628, l='MpServer', x=-284.51, y=67.00, z=-402.43], EntityInfHuman['unknown'/51629, l='MpServer', x=-278.05, y=19.30, z=-395.83], EntityButhol['unknown'/51630, l='MpServer', x=-271.70, y=20.61, z=-392.53], EntityCustom['unknown'/51631, l='MpServer', x=-286.30, y=38.00, z=-374.46], MoCEntityGoldFish['unknown'/51632, l='MpServer', x=-284.50, y=10.05, z=-359.50], MoCEntityGoldFish['unknown'/51633, l='MpServer', x=-282.50, y=9.61, z=-362.50], EntityCustom['unknown'/51634, l='MpServer', x=-287.56, y=30.00, z=-335.57], EntityItem['item.tile.mushroom.glowshroom'/51659, l='MpServer', x=-260.47, y=12.30, z=-436.88], EntityItem['item.tile.dungeontactics:bush_incindiberry'/51660, l='MpServer', x=-261.88, y=12.00, z=-432.08], EntityCustom['unknown'/51661, l='MpServer', x=-263.50, y=36.00, z=-447.50], EntityItem['item.tile.mushroom.glowshroom'/51662, l='MpServer', x=-258.53, y=12.03, z=-429.13], EntityItem['item.tile.mushroom7'/51663, l='MpServer', x=-266.50, y=29.00, z=-417.06], EntityItem['item.item.archaic_brick'/51664, l='MpServer', x=-258.57, y=18.00, z=-401.53], EntityItem['item.item.ancient_motive_core'/51665, l='MpServer', x=-259.18, y=18.00, z=-402.67], EntityItem['item.item.l_essence_of_greed'/51666, l='MpServer', x=-257.66, y=18.00, z=-401.27], EntityBat['Bat'/51667, l='MpServer', x=-272.02, y=26.03, z=-409.67], EntityCustom['unknown'/51668, l='MpServer', x=-265.76, y=57.00, z=-392.64], EntityWroughtnaut['unknown'/51669, l='MpServer', x=-266.50, y=44.00, z=-383.50], Entity_SpecialZombie['unknown'/51670, l='MpServer', x=-263.70, y=50.00, z=-370.70], MoCEntityStingRay['unknown'/51671, l='MpServer', x=-256.27, y=59.79, z=-375.40], EntityItem['item.item.raw_bat'/51672, l='MpServer', x=-266.89, y=26.00, z=-343.51], EntityItem['item.tile.pelt_bat'/51673, l='MpServer', x=-267.58, y=25.00, z=-346.20], EntityItem['item.item.l_essence_of_greed'/51674, l='MpServer', x=-265.92, y=25.00, z=-345.99], EntityBat['Bat'/51675, l='MpServer', x=-259.90, y=51.03, z=-345.17]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by Elec332** [comment] 2020-07-07 12:03
Duplicate of https://github.com/Elecs-Mods/CraftingTable-IV/issues/99

**Closed as completed by Elec332** 2020-07-07 12:03 UTC
